export const list = [
  { name: 'ALEX KASUMBA' },
  { name: 'Santosh Bishwokarma' },
  { name: 'Maribel Aragon' },
  { name: 'Nova Alimes' },
  { name: 'Abdulqader Vaid' },
  { name: 'Helberto Hallera' },
  { name: 'Sweetcel Jusi' },
  { name: 'Shaham Saeed Khan' },
  { name: 'Hebatallah Hussein' },
  { name: 'Ayo Abdul-Azeez' },
  { name: 'Anil Chandran' },
  { name: 'Erickson vaz' },
  { name: 'Deepak Guleria' },
  { name: 'John Kennedy Montuya' },
  { name: 'Muhammad Anees ur Rehman' },
  { name: 'Bryan (Bry) Pineda' },
  { name: 'Nay Che Yadanar' },
  { name: 'Farhan Shakil' },
  { name: 'Mirza Fraz' },
  { name: 'Santhosh Kumar	' },
];
